summary: List all products
description: Retrieve a list of available products in the store.
responses:
  200:
    description: An array of products
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Example Product"
        price:
          type: number
          format: float
          example: 19.99
